// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/article/get/{id}": {
            "get": {
                "description": "调用获取文章信息",
                "produces": [
                    "application/json"
                ],
                "summary": "查询文章信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "文章ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {}
                }
            }
        },
        "/api/article/{cid}/{pi}/{ps}": {
            "get": {
                "description": "根据文章分类获取数据",
                "produces": [
                    "application/json"
                ],
                "summary": "根据文章分类获取数据",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分类ID",
                        "name": "cid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前页数",
                        "name": "pi",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "一页显示多少数据",
                        "name": "ps",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {}
                }
            }
        },
        "/api/class/all": {
            "get": {
                "description": "获取所有分类",
                "produces": [
                    "application/json"
                ],
                "summary": "获取所有分类",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {}
                }
            }
        },
        "/api/class/get/{id}": {
            "get": {
                "description": "查询一个分类的详细信息",
                "produces": [
                    "application/json"
                ],
                "summary": "查询单个分类",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分类ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {}
                }
            }
        },
        "/api/class/page/{pi}/{ps}": {
            "get": {
                "description": "分类按分页获取",
                "produces": [
                    "application/json"
                ],
                "summary": "分类按分页获取",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "当前页数",
                        "name": "pi",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "一页显示多少数据",
                        "name": "ps",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {}
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "127.0.0.1:801",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "在线api接口文档",
	Description: "在线api接口文档",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
