basePath: /
host: localhost:801
info:
  contact: {}
  description: 简易api描述文档.
  license: {}
  title: Swagger Example API
  version: "1.0"
paths:
  /api/article/all:
    get:
      description: 获取article表中的所有数据，慎用
      produces:
      - application/json
      responses:
        "200": {}
        "500": {}
      summary: 查询所有文章
  /api/article/get/{id}:
    get:
      description: 打开一篇文章，并获取信息
      parameters:
      - description: ARTICLE_ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
      summary: 获取一篇文章信息
  /api/class/get/{id}:
    get:
      description: 查询一条分类
      produces:
      - application/json
      responses:
        "200": {}
        "500": {}
      summary: 查询一条分类
  /login:
    post:
      consumes:
      - application/json
      description: 判断用户是否登陆成功
      produces:
      - application/json
      responses:
        "200": {}
        "500": {}
      summary: 用户登陆
swagger: "2.0"
